version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: reactive_postgres
    environment:
      POSTGRES_USER: reactive_user
      POSTGRES_PASSWORD: reactive_pass
      POSTGRES_DB: reactive_db
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: